import Head from "next/head"
import "bootstrap/dist/css/bootstrap.min.css"
import TaskList from "@/components/TasksList"

export default function Home() {
  return (
    <>
      <Head>
        <title>Employee Task Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container mt-4">
        <h1 className="text-center mb-4">Employee Task Management</h1>
        <TaskList />
      </div>
    </>
  );
}
