import Head from "next/head"
import "bootstrap/dist/css/bootstrap.min.css"
import Tambah from "@/components/TambahTugas"

export default function tambah() {
    return (
        <>
            <Head>
                <title>Tambah Tugas Baru</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className="container mt-4">
                <h1 className="text-center mb-4">Tambah Tugas Baru</h1>
                <Tambah />
            </div>
        </>
    );
}
